### ISSUE TITLE
Is this line correct?

### ISSUE THREAD

**Issue by eternauta123** [conor19w/Binance-Futures-Bot#24]
https://github.com/conor19w/Binance-Futures-Bot/blob/a962a0d9505b1c2afcd0f4ec53cdbbd13074d41e/Bot_Class.py#L140

Is this line correct? Or should it be referencing -1 index on OPEN_H? 
It is an append statement so for example:
Close_H length =300
Open_H length =300
                        self.Close_H.append((self.Open[-1] + self.Close[-1] + self.Low[-1] + self.High[-1]) / 4)
Close_H length =301
Open_H length =300
Current:
self.Open_H.append((self.Open_H[-2] + self.Close_H[-2]) / 2)-> self.Open_H.append((self.Open_H[**-299**] + self.Close_H[**-300**]) / 2)
What may be the correction:
self.Open_H.append((self.Open_H[**-1**] + self.Close_H[-2]) / 2) -> self.Open_H.append((self.Open_H[**-300**] + self.Close_H[**-300**]) / 2)

Close_H length =301
Open_H length =301

**Comment by conor19w** [comment]
Looked into issue with heikin ashi and fixed it through trial and error, should be good now I printed out values and compared to Binance's Prices.
Your solution worked but I still don't get why I didn't have to alter the logic in add_hist() as I should run into the same issue...
Thanks for the help

**Comment by eternauta123** [comment]
Connor, 
I am quite new on github collaboration I forked  your project, but accidentally uploaded some paswords so i deleted it.

I wanted to make some pull requests, bit now is so different in some stuff and i am just testing what i am really usingn that I am afraid I won’t.

I will share my project with you.

The main I implemented that you may use is:
- I implemented something like a manual trailing pushing SL orders according to achieved profit
-I created something that i call trust index, depending on it, i increase tolerance by 2 or 3 times (i use ema200 and rsi to increase the index), so if SL is setup to 1.5% and EMA200 and RSi are favorable, I use 4.5% SL
-i created 2 SL, one to start and one after tendency is confirmed (iI wait N candles to correct SL ). I dis this because i was hitting stop loose many times and if it was higher I would have not. So dor example  I start with 5% SL and after 0.5 candles or 1 candle, i reduce to 2.5%.
-i am using limit orders instead of market, with some logic to define the price,

Thank you very much!
