### ISSUE TITLE
Live_Bot.py - ImportError: cannot import name 'ThreadedWebsocketManager' from 'binance'

### ISSUE THREAD

**Issue by daerco22** [conor19w/Binance-Futures-Bot#25]
Hi I encounter this import error when running "python3 app.py" also I've already check the cause of the issue and to solve it we just need to add .streams when importing ThreadedWebsocketManager from binance. Thanks.

Live_Bot.py:
from pprint import PrettyPrinter
import sys, os
from binance.client import Client
from binance.exceptions import BinanceAPIException
**_from binance.streams import ThreadedWebsocketManager_**
from datetime import datetime, date, timedelta
from threading import Thread
from multiprocessing import Process, Pipe
import time

<img width="666" alt="image" src="https://user-images.githubusercontent.com/41880759/180706217-63665b33-c263-4457-ae2b-1336094d07a4.png">

**Comment by conor19w** [comment]
Hey did you install the requirements?
```shell
pip install -r requirements.txt
```

**Comment by Yhon560** [comment]
> Hey did you install the requirements?
> 
> ```shell
> pip install -r requirements.txt
> ```
pip innstal error

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
unicorn-binance-websocket-api 1.41.0 requires websockets==10.3, but you have websockets 9.1 which is incompatible.
Successfully installed websockets-9.1

**Comment by conor19w** [comment]
Sounds like a pip error, you'll have to look on the internet for a generic solution

**Comment by Yhon560** [comment]
> Sounds like a pip error, you'll have to look on the internet for a generic solution

oke work unistal python and instal last version 


python -m pip install --upgrade -r requirements.txt
